name: t2
on: 
  push:
env:
  WF_ENV: All jobs
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: only steps in this job
    steps:
      - name: log ENV var
        env:
          STEP_ENV: only this step
        run: |
          echo "WF_ENV: ${WF_ENV}"   
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}" 
      - name: List files
        run: |
          pwd
          echo "STEP_ENV: ${STEP_ENV}"   
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Default
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Push a random file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{
          secrets.GITHUB_TOKEN }}@github.com/
          $GITHUB_REPOSITORY.git"
          git config --global user.email jjbanovic@gmail.com
          git config --global user.name "jerolim" 
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m"Random"
          git push

              
        
